/**
 * @author  smxrtsp
 * @file    b_sig.h
 *
 * THIS FILE WAS GENERATED BY THE STREAMIX TOOL `smxtrsp`. DO NOT EDIT THIS
 * FILE EDIT THE ORIGINAL STREAMIX-SOURCE FILE INSTEAD!
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN WHEN RECOMPILING THE
 * STREAMIX-SOURCE FILE!
 *
 * The header file of the implementation of the streamix box b.
 *
 * The box has the following signature:
 *
 *   - in x (use SMX_CHANNEL_READ( h, b, x ) to read)
 *   - in y (use SMX_CHANNEL_READ( h, b, y ) to read)
 */

#ifndef BOX_b_SIG_H
#define BOX_b_SIG_H

/**
 * The input signature of b
 */
enum ports_b_in_e
{
    SMX_PORT_IDX_b_in_x,
    SMX_PORT_IDX_b_in_y,
};

/**
 * The output signature of b
 */
enum ports_b_out_e
{
    SMX_PORT_IDX_b_out_EMPTY,
};

#endif
