/**
 * @author  smxrtsp
 * @file    r_sig.h
 *
 * THIS FILE WAS GENERATED BY THE STREAMIX TOOL `smxtrsp`. DO NOT EDIT THIS
 * FILE EDIT THE ORIGINAL STREAMIX-SOURCE FILE INSTEAD!
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN WHEN RECOMPILING THE
 * STREAMIX-SOURCE FILE!
 *
 * The header file of the implementation of the streamix box r.
 *
 * The box has the following signature:
 *
 *   - in x (use SMX_CHANNEL_READ( h, r, x ) to read)
 */

#ifndef BOX_r_SIG_H
#define BOX_r_SIG_H

/**
 * The input signature of r
 */
enum ports_r_in_e
{
    SMX_PORT_IDX_r_in_x,
};

/**
 * The output signature of r
 */
enum ports_r_out_e
{
    SMX_PORT_IDX_r_out_EMPTY,
};

#endif
