/**
 * @author  smxrtsp
 * @file    a_sig.h
 *
 * THIS FILE WAS GENERATED BY THE STREAMIX TOOL `smxtrsp`. DO NOT EDIT THIS
 * FILE EDIT THE ORIGINAL STREAMIX-SOURCE FILE INSTEAD!
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN WHEN RECOMPILING THE
 * STREAMIX-SOURCE FILE!
 *
 * The header file of the implementation of the streamix box a.
 *
 * The box has the following signature:
 *
 *   - out x (use SMX_CHANNEL_WRITE( h, a, x, msg ) to write)
 */

#ifndef BOX_a_SIG_H
#define BOX_a_SIG_H

/**
 * The input signature of a
 */
enum ports_a_in_e
{
    SMX_PORT_IDX_a_in_EMPTY,
};

/**
 * The output signature of a
 */
enum ports_a_out_e
{
    SMX_PORT_IDX_a_out_x,
};

#endif
