/**
 * @file tb.c
 *
 * THIS FILE WAS GENERATED BY THE STREAMIX TOOL `smxtrsp`. DO NOT EDIT THIS
 * FILE EDIT THE ORIGINAL STREAMIX-SOURCE FILE `tb.smx` INSTEAD!
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN WHEN RECOMPILING THE
 * STREAMIX-SOURCE FILE!
 *
 * The main file which builds the streamix network and starts each net.
 */

#include "smxrts.h"
#include "a.h"
#include "b.h"

int main( void )
{
    SMX_PROGRAM_INIT();

    SMX_NET_CREATE( 0, A1, a );
    SMX_NET_INIT( 0, 0, 1 );
    SMX_NET_CREATE( 1, A2, a );
    SMX_NET_INIT( 1, 0, 1 );
    SMX_NET_CREATE( 2, B, b );
    SMX_NET_INIT( 2, 2, 0 );
    SMX_CHANNEL_CREATE( 0, 1, SMX_D_FIFO, x );
    SMX_CONNECT( 1, 0, a, x, out );
    SMX_CONNECT( 2, 0, b, y, in );
    SMX_CONNECT_GUARD( 0, 0, 20000000 );
    SMX_CHANNEL_CREATE( 1, 1, SMX_FIFO, x );
    SMX_CONNECT( 0, 1, a, x, out );
    SMX_CONNECT( 2, 1, b, x, in );
    SMX_CONNECT_GUARD( 1, 0, 20000000 );

    SMX_PROGRAM_INIT_RUN();

    SMX_NET_RUN( 0, a, 0 );
    SMX_NET_RUN( 1, a, 0 );
    SMX_NET_RUN( 2, b, 0 );

    SMX_NET_WAIT_END( 0 );
    SMX_NET_WAIT_END( 1 );
    SMX_NET_WAIT_END( 2 );

    SMX_CHANNEL_DESTROY( 0 );
    SMX_CHANNEL_DESTROY( 1 );
    SMX_NET_DESTROY( 0 );
    SMX_NET_DESTROY( 1 );
    SMX_NET_DESTROY( 2 );

    SMX_PROGRAM_CLEANUP();
}
