/**
 * @author  smxrtsp
 * @file    m_sig.h
 *
 * THIS FILE WAS GENERATED BY THE STREAMIX TOOL `smxtrsp`. DO NOT EDIT THIS
 * FILE EDIT THE ORIGINAL STREAMIX-SOURCE FILE INSTEAD!
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN WHEN RECOMPILING THE
 * STREAMIX-SOURCE FILE!
 *
 * The header file of the implementation of the streamix box m.
 *
 * The box has the following signature:
 *
 *   - in x (use SMX_CHANNEL_READ( h, m, x ) to read)
 *   - out x (use SMX_CHANNEL_WRITE( h, m, x, msg ) to write)
 */

#ifndef BOX_m_SIG_H
#define BOX_m_SIG_H

/**
 * The input signature of m
 */
enum ports_m_in_e
{
    SMX_PORT_IDX_m_in_x,
};

/**
 * The output signature of m
 */
enum ports_m_out_e
{
    SMX_PORT_IDX_m_out_x,
};

#endif
